/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/planets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all planets
         * @description It's easy to say you know them all, but do you really? Retrieve all the planets and check whether you missed one.
         */
        get: operations["getAllData"];
        put?: never;
        /**
         * Create a planet
         * @description Time to play god and create a new planet. What do you think? Ah, don't think too much. What could go wrong anyway?
         */
        post: operations["createPlanet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planets/{planetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a planet
         * @description You'll better learn a little bit more about the planets. It might come in handy once space travel is available for everyone.
         */
        get: operations["getPlanet"];
        /**
         * Update a planet
         * @description Sometimes you make mistakes, that's fine. No worries, you can update all planets.
         */
        put: operations["updatePlanet"];
        post?: never;
        /**
         * Delete a planet
         * @description This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for planets with life. So, this endpoint is now deprecated and should not be used anymore.
         */
        delete: operations["deletePlanet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planets/{planetId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an image to a planet
         * @description Got a crazy good photo of a planet? Share it with the world!
         */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/celestial-bodies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a celestial body */
        post: operations["createCelestialBody"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user
         * @description Time to create a user account, eh?
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a token
         * @description Yeah, this is the boring security stuff. Just get your super secret token and move on.
         */
        post: operations["getToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authenticated user
         * @description Find yourself they say. That's what you can do here.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = {
    newPlanet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Information about a new planet */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Planet"];
                    "application/xml": components["schemas"]["Planet"];
                };
            };
            responses: {
                /** @description Return a 200 status to indicate that the data was received successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type components = {
    schemas: {
        /** @description A user */
        User: {
            /** Format: int64 */
            readonly id?: number;
            name?: string;
        };
        /** @description Credentials to authenticate a user */
        Credentials: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description A token to authenticate a user */
        Token: {
            token?: string;
        };
        /** @description A celestial body which can be either a planet or a satellite */
        CelestialBody: components["schemas"]["Planet"] | components["schemas"]["Satellite"];
        /** @description A planet in the Scalar Galaxy */
        Planet: {
            /** Format: int64 */
            readonly id: number;
            name: string;
            description?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "planet";
            /**
             * Format: float
             * @description A score from 0 to 1 indicating potential habitability
             */
            habitabilityIndex?: number;
            physicalProperties?: {
                /**
                 * Format: float
                 * @description Mass in Earth masses (must be greater than 0)
                 */
                mass?: number;
                /**
                 * Format: float
                 * @description Radius in Earth radii (must be greater than 0)
                 */
                radius?: number;
                /**
                 * Format: float
                 * @description Surface gravity in Earth g
                 */
                gravity?: number;
                temperature?: {
                    /**
                     * Format: float
                     * @description Minimum temperature in Kelvin
                     */
                    min?: number;
                    /**
                     * Format: float
                     * @description Maximum temperature in Kelvin
                     */
                    max?: number;
                    /**
                     * Format: float
                     * @description Average temperature in Kelvin
                     */
                    average?: number;
                } & {
                    [key: string]: number;
                };
            } & {
                [key: string]: number;
            };
            /** @description Atmospheric composition */
            atmosphere?: ({
                compound?: string;
                /** Format: float */
                percentage?: number;
            } & {
                [key: string]: string;
            })[];
            /** Format: date-time */
            discoveredAt?: string;
            image?: string | null;
            satellites?: components["schemas"]["Satellite"][];
            creator?: components["schemas"]["User"];
            tags?: string[];
            /** Format: date-time */
            readonly lastUpdated?: string;
            /**
             * Format: uri
             * @description URL which gets invoked upon a successful operation
             */
            successCallbackUrl?: string;
            /**
             * Format: uri
             * @description URL which gets invoked upon a failed operation
             */
            failureCallbackUrl?: string;
        };
        /** @description Every satellite in the Scalar Galaxy */
        Satellite: {
            /** Format: int64 */
            readonly id?: number;
            name: string;
            description?: string | null;
            /**
             * Format: float
             * @description Diameter in kilometers
             */
            diameter?: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "satellite";
            orbit?: {
                /**
                 * Format: int64
                 * @description The ID of the planet this satellite orbits
                 */
                planetId?: number;
                /**
                 * Format: float
                 * @description Orbital period in Earth days
                 */
                orbitalPeriod?: number;
                /**
                 * Format: float
                 * @description Average distance from the planet in kilometers
                 */
                distance?: number;
            };
        };
        /** @description A paginated resource */
        PaginatedResource: {
            meta?: {
                /** Format: int64 */
                limit?: number;
                /** Format: int64 */
                offset?: number;
                /** Format: int64 */
                total?: number;
                next?: string | null;
            };
        };
        /** @description Message about an image upload */
        ImageUploadedMessage: {
            message?: string;
            /** @description The URL where the uploaded image can be accessed */
            imageUrl?: string;
            /**
             * Format: date-time
             * @description Timestamp when the image was uploaded
             */
            uploadedAt?: string;
            /** @description Size of the uploaded image in bytes */
            fileSize?: number;
            /** @description The content type of the uploaded image */
            mimeType?: string;
        };
        /** @description RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807) */
        BadRequestError: {
            type?: string;
            title?: string;
            /** Format: int64 */
            status?: number;
            detail?: string;
        };
        /** @description RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807) */
        ForbiddenError: {
            type?: string;
            title?: string;
            /** Format: int64 */
            status?: number;
            detail?: string;
        };
        /** @description RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807) */
        NotFoundError: {
            type?: string;
            title?: string;
            /** Format: int64 */
            status?: number;
            detail?: string;
        };
        /** @description RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807) */
        UnauthorizedError: {
            type?: string;
            title?: string;
            /** Format: int64 */
            status?: number;
            detail?: string;
        };
        /** @description RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807) */
        Conflict: {
            type?: string;
            title?: string;
            /** Format: int64 */
            status?: number;
            detail?: string;
        };
        /** @description RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807) */
        UnprocessableEntity: {
            type?: string;
            title?: string;
            /** Format: int64 */
            status?: number;
            detail?: string;
        };
    };
    responses: {
        /** @description Image uploaded */
        ImageUploaded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ImageUploadedMessage"];
                "application/xml": components["schemas"]["ImageUploadedMessage"];
            };
        };
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BadRequestError"];
                "application/xml": components["schemas"]["BadRequestError"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ForbiddenError"];
                "application/xml": components["schemas"]["ForbiddenError"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NotFoundError"];
                "application/xml": components["schemas"]["NotFoundError"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnauthorizedError"];
                "application/xml": components["schemas"]["UnauthorizedError"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Conflict"];
                "application/xml": components["schemas"]["Conflict"];
            };
        };
        /** @description Unprocessable Entity */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnprocessableEntity"];
                "application/xml": components["schemas"]["UnprocessableEntity"];
            };
        };
    };
    parameters: {
        /** @description The ID of the planet to get */
        planetId: number;
        /** @description The ID of the satellite to get */
        satelliteId: number;
        /** @description The number of items to return */
        limit: number;
        /** @description The number of items to skip before starting to collect the result set */
        offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    getAllData: {
        parameters: {
            query?: {
                /** @description The number of items to return */
                limit?: components["parameters"]["limit"];
                /** @description The number of items to skip before starting to collect the result set */
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Planet"][];
                    } & components["schemas"]["PaginatedResource"];
                    "application/xml": {
                        data?: components["schemas"]["Planet"][];
                    } & components["schemas"]["PaginatedResource"];
                };
            };
        };
    };
    createPlanet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Planet */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Planet"];
                "application/xml": components["schemas"]["Planet"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Planet"];
                    "application/xml": components["schemas"]["Planet"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getPlanet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the planet to get */
                planetId: components["parameters"]["planetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Planet Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Planet"];
                    "application/xml": components["schemas"]["Planet"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePlanet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the planet to get */
                planetId: components["parameters"]["planetId"];
            };
            cookie?: never;
        };
        /** @description New information about the planet */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Planet"];
                "application/xml": components["schemas"]["Planet"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Planet"];
                    "application/xml": components["schemas"]["Planet"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePlanet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the planet to get */
                planetId: components["parameters"]["planetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the planet to get */
                planetId: components["parameters"]["planetId"];
            };
            cookie?: never;
        };
        /** @description Image to upload */
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The image file to upload
                     */
                    image?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["ImageUploaded"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCelestialBody: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CelestialBody"];
            };
        };
        responses: {
            /** @description Celestial body created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CelestialBody"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User to create */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"] & components["schemas"]["Credentials"];
                "application/xml": components["schemas"]["User"] & components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                    "application/xml": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Credentials to authenticate a user */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Credentials"];
                "application/xml": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Token Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                    "application/xml": components["schemas"]["Token"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                    "application/xml": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
