/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/cats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Will return all cats */
        get: operations["api:cats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Count how many cat */
        get: operations["api:count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Will return all tags */
        get: operations["api:tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a random cat */
        get: operations["cat:random"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cat/says/{text}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get random cat saying text */
        get: operations["cat:random:text"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cat/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get cat by id */
        get: operations["cat:get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cat/{id}/says/{text}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get cat by id saying text */
        get: operations["cat:get:text"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cat/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get random cat by tag */
        get: operations["cat:random:tag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cat/{tag}/says/{text}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get random cat by tag saying text */
        get: operations["cat:random:tag:text"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Cat: {
            id: string;
            tags: string[];
            mimetype: string;
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "api:cats": {
        parameters: {
            query?: {
                limit?: number;
                skip?: number;
                tags?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of cats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cat"][];
                };
            };
        };
    };
    "api:count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        count?: number;
                    };
                };
            };
        };
    };
    "api:tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    "cat:random": {
        parameters: {
            query?: {
                type?: "square" | "medium" | "small" | "xsmall";
                filter?: "mono" | "negate" | "custom";
                fit?: "cover" | "contain" | "fill" | "inside" | "outside";
                position?: "top" | "right top" | "right" | "right bottom" | "bottom" | "left bottom" | "left" | "left top" | "center";
                width?: number;
                height?: number;
                blur?: number;
                /** @description With custom filter, define red value between 0 and 255 */
                r?: number;
                /** @description With custom filter, define green value between 0 and 255 */
                g?: number;
                /** @description With custom filter, define blue value between 0 and 255 */
                b?: number;
                /** @description With custom filter, define brightness */
                brightness?: number;
                /** @description With custom filter, define saturation */
                saturation?: number;
                /** @description With custom filter, define hue */
                hue?: number;
                /** @description With custom filter, define lightness */
                lightness?: number;
                html?: boolean;
                json?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/json": components["schemas"]["Cat"];
                };
            };
        };
    };
    "cat:random:text": {
        parameters: {
            query?: {
                type?: "square" | "medium" | "small" | "xsmall";
                filter?: "mono" | "negate" | "custom";
                fit?: "cover" | "contain" | "fill" | "inside" | "outside";
                position?: "top" | "right top" | "right" | "right bottom" | "bottom" | "left bottom" | "left" | "left top" | "center";
                width?: number;
                height?: number;
                blur?: number;
                /** @description With custom filter, define red value between 0 and 255 */
                r?: number;
                /** @description With custom filter, define green value between 0 and 255 */
                g?: number;
                /** @description With custom filter, define blue value between 0 and 255 */
                b?: number;
                /** @description With custom filter, define brightness */
                brightness?: number;
                /** @description With custom filter, define saturation */
                saturation?: number;
                /** @description With custom filter, define hue */
                hue?: number;
                /** @description With custom filter, define lightness */
                lightness?: number;
                html?: boolean;
                json?: boolean;
                font?: "Andale Mono" | "Impact" | "Arial" | "Arial Black" | "Comic Sans MS" | "Courier New" | "Georgia" | "Times New Roman" | "Verdana" | "Webdings";
                fontSize?: number;
                fontColor?: string;
                fontBackground?: string;
            };
            header?: never;
            path: {
                text: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/json": components["schemas"]["Cat"];
                };
            };
        };
    };
    "cat:get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/json": components["schemas"]["Cat"];
                };
            };
            /** @description Cat not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "cat:get:text": {
        parameters: {
            query?: {
                type?: "square" | "medium" | "small" | "xsmall";
                filter?: "mono" | "negate" | "custom";
                fit?: "cover" | "contain" | "fill" | "inside" | "outside";
                position?: "top" | "right top" | "right" | "right bottom" | "bottom" | "left bottom" | "left" | "left top" | "center";
                width?: number;
                height?: number;
                blur?: number;
                /** @description With custom filter, define red value between 0 and 255 */
                r?: number;
                /** @description With custom filter, define green value between 0 and 255 */
                g?: number;
                /** @description With custom filter, define blue value between 0 and 255 */
                b?: number;
                /** @description With custom filter, define brightness */
                brightness?: number;
                /** @description With custom filter, define saturation */
                saturation?: number;
                /** @description With custom filter, define hue */
                hue?: number;
                /** @description With custom filter, define lightness */
                lightness?: number;
                html?: boolean;
                json?: boolean;
                font?: "Andale Mono" | "Impact" | "Arial" | "Arial Black" | "Comic Sans MS" | "Courier New" | "Georgia" | "Times New Roman" | "Verdana" | "Webdings";
                fontSize?: number;
                fontColor?: string;
                fontBackground?: string;
            };
            header?: never;
            path: {
                id: string;
                text: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/json": components["schemas"]["Cat"];
                };
            };
            /** @description Cat not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "cat:random:tag": {
        parameters: {
            query?: {
                type?: "square" | "medium" | "small" | "xsmall";
                filter?: "mono" | "negate" | "custom";
                fit?: "cover" | "contain" | "fill" | "inside" | "outside";
                position?: "top" | "right top" | "right" | "right bottom" | "bottom" | "left bottom" | "left" | "left top" | "center";
                width?: number;
                height?: number;
                blur?: number;
                /** @description With custom filter, define red value between 0 and 255 */
                r?: number;
                /** @description With custom filter, define green value between 0 and 255 */
                g?: number;
                /** @description With custom filter, define blue value between 0 and 255 */
                b?: number;
                /** @description With custom filter, define brightness */
                brightness?: number;
                /** @description With custom filter, define saturation */
                saturation?: number;
                /** @description With custom filter, define hue */
                hue?: number;
                /** @description With custom filter, define lightness */
                lightness?: number;
                html?: boolean;
                json?: boolean;
            };
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/json": components["schemas"]["Cat"];
                };
            };
        };
    };
    "cat:random:tag:text": {
        parameters: {
            query?: {
                type?: "square" | "medium" | "small" | "xsmall";
                filter?: "mono" | "negate" | "custom";
                fit?: "cover" | "contain" | "fill" | "inside" | "outside";
                position?: "top" | "right top" | "right" | "right bottom" | "bottom" | "left bottom" | "left" | "left top" | "center";
                width?: number;
                height?: number;
                blur?: number;
                /** @description With custom filter, define red value between 0 and 255 */
                r?: number;
                /** @description With custom filter, define green value between 0 and 255 */
                g?: number;
                /** @description With custom filter, define blue value between 0 and 255 */
                b?: number;
                /** @description With custom filter, define brightness */
                brightness?: number;
                /** @description With custom filter, define saturation */
                saturation?: number;
                /** @description With custom filter, define hue */
                hue?: number;
                /** @description With custom filter, define lightness */
                lightness?: number;
                html?: boolean;
                json?: boolean;
                font?: "Andale Mono" | "Impact" | "Arial" | "Arial Black" | "Comic Sans MS" | "Courier New" | "Georgia" | "Times New Roman" | "Verdana" | "Webdings";
                fontSize?: number;
                fontColor?: string;
                fontBackground?: string;
            };
            header?: never;
            path: {
                tag: string;
                text: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/json": components["schemas"]["Cat"];
                };
            };
        };
    };
}
